image:
  file: .gitpod.Dockerfile

# Commands that will run on workspace start
tasks:
  - name: Setup, Install & Build
    init: pnpm run bootstrap
    command: pnpm run dev
    env:
      PUBLIC_UNDB_ADMIN_EMAIL: test@example.com
      PUBLIC_UNDB_ADMIN_PASSWORD: 123456
      UNDB_SEED: true

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
    name: undb
    description: undb Preview
