name: CI

on:
  push:
    branches: ['develop']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    env:
      TZ: UTC
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.6.1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.7.6

      - name: Install dependencies
        run: pnpm install

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm build

      - name: Test
        run: pnpm test
